spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=utf-8
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    password: 123
server:
  port: 8082
mybatis:
  mapper-locations:  classpath:/mapper/*.xml
  type-aliases-package: com.bdqn.entity