spring:
  datasource:
    url: jdbc\:mysql\:///exam?characterEncoding\=utf8&allowMultiQueries\=true
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    data-password: 123
server:
  port: 8080
mybatis:
  mapper-locations:  classpath:*.xml
  type-aliases-package: cn.bdqn.entity